name: ci
on: 'push'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          yarn
          yarn build
          yarn lint
